# Generated by Django 3.1.1 on 2021-01-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(db_index=True, max_length=128, verbose_name='Config Key')),
                ('config_id', models.CharField(db_index=True, max_length=128, verbose_name='Config ID')),
                ('config', models.TextField(default='{}', verbose_name='Configuration')),
                ('time_added', models.DateTimeField(auto_now_add=True, verbose_name='Time Added')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Time Updated')),
            ],
            options={
                'unique_together': {('config_key', 'config_id')},
            },
        ),
    ]
