# Generated by Django 3.1.4 on 2021-01-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_keys', models.TextField(verbose_name='Input Keys (Comma separated)')),
                ('output_keys', models.TextField(verbose_name='Output Keys (Comma separated)')),
                ('rules', models.TextField(default='[]', verbose_name='Rules')),
                ('time_added', models.DateTimeField(auto_now_add=True, verbose_name='Time Added')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Time Updated')),
            ],
        ),
    ]
