# Generated by Django 3.1.4 on 2021-01-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonrule',
            name='input_keys',
            field=models.TextField(default='[]', verbose_name='Input Keys'),
        ),
        migrations.AlterField(
            model_name='commonrule',
            name='output_keys',
            field=models.TextField(default='[]', verbose_name='Output Keys'),
        ),
    ]
