# Generated by Django 3.1.4 on 2021-01-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0002_auto_20210104_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstraintRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='CommonRule',
            new_name='ConfigRule',
        ),
    ]
