# Generated by Django 3.1.4 on 2020-12-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonConfig',
        ),
    ]
