# Generated by Django 3.1.4 on 2020-12-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('km', '0002_remove_concept_is_abstract'),
        ('config', '0002_delete_commonconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.CharField(db_index=True, max_length=128, verbose_name='Config ID')),
                ('config', models.TextField(default='{}', verbose_name='Configuration')),
                ('time_added', models.DateTimeField(auto_now_add=True, verbose_name='Time Added')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Time Updated')),
                ('config_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='km.concept')),
            ],
            options={
                'unique_together': {('config_for', 'config_id')},
            },
        ),
    ]
