# Generated by Django 3.1.4 on 2021-01-04 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_auto_20210104_1003'),
        ('config', '0003_commonconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonconfig',
            name='config_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='state.state'),
        ),
    ]
