# Generated by Django 3.1.4 on 2020-12-24 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('name_readable', models.CharField(max_length=128, unique=True, verbose_name='Readable name')),
                ('is_abstract', models.BooleanField(default=False)),
                ('time_added', models.DateTimeField(auto_now_add=True, verbose_name='Time Added')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Time Updated')),
                ('is_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='km.concept', verbose_name='Parent Concept')),
            ],
        ),
        migrations.CreateModel(
            name='Attr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('name_readable', models.CharField(max_length=128, verbose_name='Readable name')),
                ('options', models.TextField(blank=True, default='{\n    "type": "string",\n    "default": null,\n    "container": null,\n    "container_config": {}\n}', null=True, verbose_name='Attr options')),
                ('time_added', models.DateTimeField(auto_now_add=True, verbose_name='Time Added')),
                ('time_updated', models.DateTimeField(auto_now=True, verbose_name='Time Updated')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='km.concept')),
            ],
            options={
                'unique_together': {('concept', 'name')},
            },
        ),
    ]
