# Generated by Django 3.1.4 on 2021-01-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('km', '0002_remove_concept_is_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attr',
            name='options',
            field=models.TextField(blank=True, default='{\n    "type": "string",\n    "required": true,\n    "default": null,\n    "container": null,\n    "container_config": {}\n}', null=True, verbose_name='Attr options'),
        ),
    ]
