"""
Django settings for djangogo project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from core.utils import ConfigWriterWithRepeatKeys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'j-s&#fnl*ua%x3r61m^at!m6g(cd%ioxh0m=mb!kfg4l%f@(ej'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangogo.urls'

PROJECT_TAG = 'djangogo_default_project'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangogo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = f'/tmp/{PROJECT_TAG}/static_root/'  # Change this as needed

AUTH_USER_MODEL = 'accounts.User'


UWSGI_CONFIG = ConfigWriterWithRepeatKeys()
UWSGI_CONF_FILENAME = os.path.join(BASE_DIR, 'run', f'uwsgi.{PROJECT_TAG}.ini')

UWSGI_INSTANCE_CONFIG = {
    'env': 'DJANGO_SETTINGS_MODULE=djangogo.settings',
    'chdir': BASE_DIR,
    'module': WSGI_APPLICATION.replace('.application', ':application'),
    'master': 'true',
    'pidfile': os.path.join(BASE_DIR, 'run', f'uwsgi.{PROJECT_TAG}.pid'),
    'http': ['0.0.0.0:8000'],
    'socket': '127.0.0.1:0',
    'harakiri': '20',
    'vacuum': 'true',
    'processes': '2',
    'threads': '2',
    'enable-threads': 'true',
    'no-threads-wait': 'true',
    'max-requests': '5000',
    'max-requests-delta': '3',
    'lazy-apps': 'true',
    'touch-chain-reload': os.path.join(BASE_DIR, 'run', f'uwsgi.{PROJECT_TAG}.touch'),
    'disable-logging': 'false',
    'log-master': 'true',  # delegate logging to master process
    'stats': '0.0.0.0:9191',
    'stats-http': 'true',
    'static-map': [f'/static={STATIC_ROOT}'],
}

UWSGI_CONFIG.add_section('uwsgi')
for setting_key in UWSGI_INSTANCE_CONFIG:
    setting_value = UWSGI_INSTANCE_CONFIG[setting_key]
    UWSGI_CONFIG.set('uwsgi', setting_key, setting_value)


