# Generated by Django 3.1.4 on 2021-01-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_auto_20210104_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='instance_id_template',
            field=models.CharField(default='', max_length=128, verbose_name='Instance ID template'),
        ),
    ]
